name: rndforest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - joblib
  - jupyter
  - ipython
  - pip

# Optional: Dev tools
  - pytest
