name: rndforest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - joblib
  - jupyter
  - ipython
  - pip
  - pytest

variables:
  PROJECT_ROOT: "/mnt/ai/projects/rndForest"
  DATASET: "/mnt/ai/projects/rndForest/data"
  MODELS_PATH: "/mnt/ai/projects/rndForest/models"
