[tool.poetry]
name = "rndforest"
version = "0.1.0"
description = "Random Forest implementation and Houdini integration"
authors = ["Suhail <suhailece@gmail.com>"]
packages = [{ include = "rndforest", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10,<4.0"
pandas = "*"
numpy = "*"
scikit-learn = "*"
joblib = "*"
uvicorn = { extras = ["standard"], version = "^0.29" }
fastapi = "^0.111"

[poetry.group.dev.dependencies]
pytest = "*"
ipython = "*"
jupyter = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
