"""baseline

Revision ID: 9368694d9931
Revises: 
Create Date: 2025-07-13 22:36:07.611367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9368694d9931'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embedding', 'vector',
               existing_type=sa.NUMERIC(precision=768),
               type_=pgvector.sqlalchemy.Vector(dim=768),
               existing_nullable=True)
    op.create_foreign_key(None, 'track', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'track', type_='foreignkey')
    op.alter_column('embedding', 'vector',
               existing_type=pgvector.sqlalchemy.Vector(dim=768),
               type_=sa.NUMERIC(precision=768),
               existing_nullable=True)
    # ### end Alembic commands ###
