"""baseline

Revision ID: 9368694d9931
Revises: 
Create Date: 2025-07-13 22:36:07.611367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '9368694d9931'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Only run type change if not SQLite
    from alembic import op
    import sqlalchemy as sa

    bind = op.get_bind()
    if bind.dialect.name != "sqlite":
        op.alter_column('embedding', 'vector',
            existing_type=sa.NUMERIC(precision=768),
            type_=pgvector.sqlalchemy.Vector(dim=768),
            existing_nullable=True)

    from alembic import op
    import sqlalchemy as sa
    
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'track', type_='foreignkey')
    op.alter_column('embedding', 'vector',
               existing_type=pgvector.sqlalchemy.Vector(dim=768),
               type_=sa.NUMERIC(precision=768),
               existing_nullable=True)
    # ### end Alembic commands ###
